[Definition]
# Example matched log:
# 2026-02-28T13:40:11Z ESS_SECURITY ... event=request_limit_exceeded ... ip=45.10.20.30 ...
failregex = ^.* ESS_SECURITY .*event=request_limit_exceeded .*ip=<HOST>(?:\s|$).*$
            ^.* ESS_SECURITY .*event=blocked_ip_request_denied .*ip=<HOST>(?:\s|$).*$
            ^.* ESS_SECURITY .*event=ip_allowlist_policy_denied .*ip=<HOST>(?:\s|$).*$

ignoreregex = ^.* ESS_SECURITY .* ip=na(?:\s|$).*$

datepattern = %%Y-%%m-%%dT%%H:%%M:%%SZ
