[Definition]
# Example matched log:
# 2026-02-28T13:40:11Z ESS_SECURITY ... event=login_failed_attempt ... ip=45.10.20.30 ...
failregex = ^.* ESS_SECURITY .*event=login_failed_attempt .*ip=<HOST>(?:\s|$).*$
            ^.* ESS_SECURITY .*event=locked_account_login_blocked .*ip=<HOST>(?:\s|$).*$
            ^.* ESS_SECURITY .*event=rapid_bruteforce_permanent_user_disable .*ip=<HOST>(?:\s|$).*$

ignoreregex = ^.* ESS_SECURITY .* ip=na(?:\s|$).*$

datepattern = %%Y-%%m-%%dT%%H:%%M:%%SZ
